Repository tahoma2d/tahoma2d, pull requests merged in 2024-12, with the labels that each got.

#1658 v1.5
  .github/ISSUE_TEMPLATE/bug_report.yml
  toonz/sources/include/tversion.h
  toonz/sources/xdg-data/org.tahoma2d.Tahoma2D.metainfo.xml
Labels: 1.5

#1660 High DPI Scaling preference
  toonz/sources/include/toonz/preferences.h
  toonz/sources/include/toonz/preferencesitemids.h
  toonz/sources/toonz/main.cpp
  toonz/sources/toonz/preferencespopup.cpp
  toonz/sources/toonzlib/preferences.cpp
Labels: 1.5.1

#1661 Fix relative drawing onion skin guided drawing
  toonz/sources/include/tools/tool.h
  toonz/sources/include/toonz/onionskinmask.h
  toonz/sources/tnztools/tool.cpp
  toonz/sources/tnztools/toonzvectorbrushtool.cpp
  toonz/sources/toonzlib/onionskinmask.cpp
Labels: 1.5.1

#1666 Column Alpha Lock
  toonz/sources/common/tfx/binaryFx.cpp
  toonz/sources/include/tfxutil.h
  toonz/sources/include/toonz/stageplayer.h
  toonz/sources/include/toonz/txshcolumn.h
  toonz/sources/include/toonz/txshlevelcolumn.h
  toonz/sources/include/toonz/txshzeraryfxcolumn.h
  toonz/sources/include/trasterfx.h
  toonz/sources/tnzbase/tfxutil.cpp
  toonz/sources/tnzbase/trasterfx.cpp
  toonz/sources/toonz/icons/dark/actions/16/alpha_locked.svg
  toonz/sources/toonz/toonz.qrc
  toonz/sources/toonz/xshcolumnviewer.cpp
  toonz/sources/toonz/xshcolumnviewer.h
  toonz/sources/toonzlib/scenefx.cpp
  toonz/sources/toonzlib/stage.cpp
  toonz/sources/toonzlib/stageplayer.cpp
  toonz/sources/toonzlib/tcolumnfx.cpp
  toonz/sources/toonzlib/txshcolumn.cpp
  toonz/sources/toonzlib/txshlevelcolumn.cpp
  toonz/sources/toonzlib/txshzeraryfxcolumn.cpp
Labels: 1.6

#1667 Reverse Clipping Mask Stacking Placement
  toonz/sources/include/toonz/stageplayer.h
  toonz/sources/include/toonz/txshcolumn.h
  toonz/sources/toonz/xshcolumnviewer.cpp
  toonz/sources/toonz/xshcolumnviewer.h
  toonz/sources/toonzlib/scenefx.cpp
  toonz/sources/toonzlib/stage.cpp
  toonz/sources/toonzlib/stageplayer.cpp
  toonz/sources/toonzlib/tcolumnfx.cpp
  toonz/sources/toonzlib/txshcolumn.cpp
  toonz/sources/toonzlib/txshlevelcolumn.cpp
Labels: 1.6

#1671 Brazilian Portuguese Translation - Review + Update to 1.5
  stuff/config/loc/Português(Brasil)/colorfx.qm
  stuff/config/loc/Português(Brasil)/image.qm
  stuff/config/loc/Português(Brasil)/tnzcore.qm
  stuff/config/loc/Português(Brasil)/tnztools.qm
  stuff/config/loc/Português(Brasil)/toonz.qm
  stuff/config/loc/Português(Brasil)/toonzlib.qm
  stuff/config/loc/Português(Brasil)/toonzqt.qm
  stuff/doc/Português((Brasil)/tips.md
  toonz/sources/translations/brazilian-portuguese/colorfx.ts
  toonz/sources/translations/brazilian-portuguese/image.ts
  toonz/sources/translations/brazilian-portuguese/tnzcore.ts
  toonz/sources/translations/brazilian-portuguese/tnztools.ts
  toonz/sources/translations/brazilian-portuguese/toonz.ts
  toonz/sources/translations/brazilian-portuguese/toonzlib.ts
  toonz/sources/translations/brazilian-portuguese/toonzqt.ts
Labels: 1.5.1
