Repository tahoma2d/tahoma2d, pull requests merged in 2024-04, with the labels that each got.

#1435 Fix Release v1.4.2
  .github/ISSUE_TEMPLATE/bug_report.yml
  appveyor.yml
  ci-scripts/osx/tahoma-buildpkg.sh
  toonz/cmake/BundleInfo.plist.in
  toonz/installer/windows/setup.iss
  toonz/sources/include/tversion.h
  toonz/sources/toonz/CMakeLists.txt
  toonz/sources/xdg-data/org.tahoma2d.Tahoma2D.metainfo.xml
Labels: 1.4.2

#1438 tahoma2d chinese translations
  stuff/config/loc/中文/colorfx.qm
  stuff/config/loc/中文/image.qm
  stuff/config/loc/中文/tnzcore.qm
  stuff/config/loc/中文/tnztools.qm
  stuff/config/loc/中文/toonz.qm
  stuff/config/loc/中文/toonzlib.qm
  stuff/config/loc/中文/toonzqt.qm
  toonz/sources/translations/chinese/colorfx.ts
  toonz/sources/translations/chinese/image.ts
  toonz/sources/translations/chinese/tnztools.ts
  toonz/sources/translations/chinese/toonz.ts
  toonz/sources/translations/chinese/toonzlib.ts
  toonz/sources/translations/chinese/toonzqt.ts
Labels: 1.4.3

#1440 Fix missing selection change notification
  toonz/sources/toonz/xshcellviewer.cpp
  toonz/sources/toonz/xshcolumnviewer.cpp
Labels: 1.5

#1445 Fix undeclared identifier errors
  toonz/sources/tnztools/toonzvectorbrushtool.cpp
  toonz/sources/tnztools/vectortapetool.cpp
Labels: 1.5

#1446 Add horizontal scrollbar to file browser
  toonz/sources/toonz/dvitemview.cpp
Labels: 1.4.3

#1450 Fix brush and eraser resizing
  toonz/sources/tnztools/fullcolorbrushtool.cpp
  toonz/sources/tnztools/fullcolorbrushtool.h
  toonz/sources/tnztools/fullcolorerasertool.cpp
  toonz/sources/tnztools/pumptool.cpp
  toonz/sources/tnztools/rastererasertool.cpp
  toonz/sources/tnztools/toonzrasterbrushtool.cpp
  toonz/sources/tnztools/toonzrasterbrushtool.h
  toonz/sources/tnztools/toonzvectorbrushtool.cpp
  toonz/sources/tnztools/toonzvectorbrushtool.h
  toonz/sources/tnztools/vectorerasertool.cpp
  toonz/sources/tnztools/vectorselectiontool.cpp
Labels: 1.4.3
