Repository tahoma2d/tahoma2d, pull requests merged in 2025-02, with the labels that each got.

#1704 Canon SDK for Linux
  .github/workflows/linux_build.yml
  .github/workflows/macOS_build.yml
  .github/workflows/windows_build.yml
  ci-scripts/linux/tahoma-build.sh
  ci-scripts/linux/tahoma-buildpkg.sh
  thirdparty/canon/.gitignore
  toonz/sources/CMakeLists.txt
  toonz/sources/stopmotion/canon.cpp
  toonz/sources/stopmotion/jpgconverter.h
  toonz/sources/toonz/CMakeLists.txt
Labels: 1.6

#1705 Fix macOS working directory path
  toonz/sources/common/tapptools/tenv.cpp
  toonz/sources/toonzfarm/tfarm/tfarmtask.cpp
  toonz/sources/toonzfarm/tfarmcontroller/tfarmcontroller.cpp
  toonz/sources/toonzfarm/tfarmserver/tfarmserver.cpp
  toonz/sources/toonzlib/thirdparty.cpp
Labels: 1.5.1

#1673 Fix Gap Closure results (Tape Tool)
  toonz/sources/common/tvectorimage/tcomputeregions.cpp
  toonz/sources/include/tools/tooloptions.h
  toonz/sources/include/tvectorimage.h
  toonz/sources/tnztools/filltool.cpp
  toonz/sources/tnztools/tooloptions.cpp
  toonz/sources/tnztools/tooloptionscontrols.cpp
  toonz/sources/tnztools/vectortapetool.cpp
  toonz/sources/toonz/tooloptionsshortcutinvoker.cpp
  toonz/sources/toonzlib/stagevisitor.cpp
Labels: 1.5.1

#1708 Fix Release v1.5.1
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  appveyor.yml
  ci-scripts/osx/tahoma-buildpkg.sh
  toonz/cmake/BundleInfo.plist.in
  toonz/installer/windows/setup.iss
  toonz/sources/include/tversion.h
  toonz/sources/toonz/CMakeLists.txt
  toonz/sources/xdg-data/org.tahoma2d.Tahoma2D.metainfo.xml
Labels: 1.5.1

#1709 Fix Task Render/Cleanup failure (Linux)
  toonz/sources/toonzfarm/tfarm/tfarmtask.cpp
  toonz/sources/toonzfarm/tfarmserver/tfarmserver.cpp
Labels: 1.5.2

#1713 Fix MOV transparency
  toonz/sources/image/ffmpeg/tiio_ff_mov.cpp
Labels: 1.5.2

#1721 Fix canceling cell/column selection
  toonz/sources/toonz/xshcellmover.cpp
  toonz/sources/toonz/xshcellmover.h
  toonz/sources/toonz/xsheetdragtool.cpp
Labels: 1.5.2

#1735 Fix Excessive Frame Range Tape lag
  toonz/sources/tnztools/vectortapetool.cpp
Labels: 1.5.2

#1733 Fix camera loading crash + improve Sony configuration
  toonz/sources/stopmotion/gphotocam.cpp
  toonz/sources/stopmotion/gphotocam.h
Labels: 1.5.2

#1744 Fix PR Cache Cleanup action
  .github/workflows/linux_build.yml
  .github/workflows/macOS_build.yml
  .github/workflows/pr_cache_cleanup.yml
  .github/workflows/windows_build.yml
Labels: 1.5.2

#1746 Fix PR Clean Branch target
  .github/workflows/pr_cache_cleanup.yml
Labels: 1.5.2

#1748 Another PR Cache Cleanup fix
  .github/workflows/pr_cache_cleanup.yml
Labels: 1.5.2

#1722 Special Modifier Key: Viewer Scrub
  toonz/sources/include/tools/cursors.h
  toonz/sources/include/toonzqt/menubarcommand.h
  toonz/sources/include/toonzqt/viewcommandids.h
  toonz/sources/tnztools/cursormanager.cpp
  toonz/sources/toonz/Resources/scrub.png
  toonz/sources/toonz/mainwindow.cpp
  toonz/sources/toonz/mainwindow.h
  toonz/sources/toonz/sceneviewer.cpp
  toonz/sources/toonz/sceneviewer.h
  toonz/sources/toonz/sceneviewerevents.cpp
  toonz/sources/toonz/shortcutpopup.cpp
  toonz/sources/toonz/toonz.qrc
Labels: 1.6

#1736 Fix alpha lock
  toonz/sources/tnzbase/trasterfx.cpp
  toonz/sources/toonzlib/stage.cpp
Labels: 1.6

#1741 Fix Testing Pull Requests (PRs) instructions
  doc/how_to_test_prs.md
  doc/testing_pr_1.JPG
  doc/testing_pr_2.JPG
  doc/testing_pr_3.JPG
  doc/testing_pr_4.JPG
  doc/testing_pr_5.JPG
Labels: 1.5.2

#1750 Increase Size of Step Lines in Motion Path
  toonz/sources/toonz/sceneviewer.cpp
Labels: 1.5.2

#1754 Fix Delete Style Color
  toonz/sources/common/tvrender/tpalette.cpp
Labels: 1.5.2
